# Generated by Django 4.2.1 on 2023-05-26 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('cid', models.CharField(max_length=46, primary_key=True, serialize=False, verbose_name='ipfs cid')),
                ('filename', models.CharField(max_length=1024, verbose_name='filename')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='image width')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='image height')),
                ('size', models.PositiveIntegerField(null=True, verbose_name='file size')),
                ('content_type', models.CharField(max_length=1024, verbose_name='content type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Upload image',
                'verbose_name_plural': 'Upload images',
            },
        ),
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('cid', models.CharField(max_length=46, primary_key=True, serialize=False, verbose_name='ipfs cid')),
                ('filename', models.CharField(max_length=1024, verbose_name='filename')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='image width')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='image height')),
                ('size', models.PositiveIntegerField(null=True, verbose_name='file size')),
                ('content_type', models.CharField(max_length=1024, verbose_name='content type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.uploadimage', verbose_name='origin image')),
            ],
            options={
                'verbose_name': 'Thumbnail image',
                'verbose_name_plural': 'Thumbnail images',
            },
        ),
    ]
