# Generated by Django 4.2.1 on 2023-06-02 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_alter_thumbnailimage_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
